# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadoPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Título')),
                ('description', models.TextField(max_length=100, verbose_name='Descrição')),
                ('dia_evento', models.DateField(verbose_name='Dia da Ocorrência')),
                ('mes_evento', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default='Janeiro')),
                ('ano_evento', models.CharField(max_length=3, verbose_name='Ano da Ocorrência')),
            ],
        ),
    ]
