# Generated by Django 2.0 on 2018-01-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadoPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Título')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('dia_evento', models.IntegerField(max_length=2, verbose_name='Dia da Ocorrência')),
                ('mes_evento', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1, verbose_name='Mês da Ocorrência')),
                ('ano_evento', models.CharField(max_length=4, verbose_name='Ano da Ocorrência')),
            ],
            options={
                'verbose_name': 'Dado Pessoal',
                'ordering': ['title'],
                'verbose_name_plural': 'Dados Pessoais',
            },
        ),
    ]
