# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadopessoal',
            name='dia_evento',
            field=models.CharField(max_length=1, verbose_name='Dia da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='dadopessoal',
            name='mes_evento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default='Janeiro', verbose_name='Mês da Ocorrência'),
        ),
    ]
