# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_auto_20170713_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadopessoal',
            name='ano_evento',
            field=models.CharField(max_length=4, verbose_name='Ano da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='dadopessoal',
            name='dia_evento',
            field=models.CharField(max_length=2, verbose_name='Dia da Ocorrência'),
        ),
    ]
