# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_auto_20170713_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadopessoal',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
    ]
